sudo: false

language: go

go: 1.5.1

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - libonig-dev
      - python3.5
      - python3.5-dev

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/axw/gocov/gocov

script:
  - go test -i ./lib
  - go test -v ./lib -covermode=count -coverprofile=coverage.cov
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
