sudo: false

language: go

go:
  - 1.7.3
  - tip

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - libonig-dev
      - python3.5
      - python3.5-dev


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/axw/gocov/gocov

script:
  - go test -i
  - go test -v -covermode=count -coverprofile=coverage.cov
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
